### ISSUE TITLE
Make it official?

### ISSUE THREAD

**Issue by danielkcz** [BlackDice/errorception#1]
@rakeshpai I am wondering if you would be willing to provide original source file for the error reporting script. I just took the minified one and "beautified" it.

I would like to eventually publish it to NPM as well under name `errorception` if you don't have objections or I can simply transfer this repo to you and you can do it yourself.

**Comment by rakeshpai** [comment]
Hey @FredyC 

I'm sorry, but this script isn't provided on npm or otherwise as a module for a reason. That's because it is a very good idea to keep Errorception's code separate from the rest of your code, and load it independently, and before your code. That's the only way to be sure that Errorception continues to work even if your code breaks, and that Errorception has coverage over all your errors, including parse-time errors. 

The script tag you get in your project is the best way to load Errorception on your page. :)

**Comment by danielkcz** [comment]
@rakeshpai Well I simply do not believe that's true. I am creating my bundle with Webpack and calling this module is a very first thing I am doing there. So unless there will be a bug in webpack boilerplate code, it has to work same way. I would say it's even faster as it doesn't have to say for extra network request.

I have been using this approach for a month now and so far everything worked just fine.

If you don't to provide source file, I understand. Do you mind me publishing this to NPM under `errorception` name?

**Comment by rakeshpai** [comment]
@FredyC I think I need to expand on what I said above.
- Any load-time or parse-time error that happens with your code, either due to syntax or build errors, or due to network errors, will cause Errorception also to stop working if it is bundled with your code. This is because of the way browsers handle JS loading - either the whole file works, or the whole file fails. These errors are what I'd consider critical errors, and such errors won't be reported by Errorception if it's bundled. However, this has a much better chance of working if Errorception is loaded separately.
- The script tag that you insert on the page - the inline script itself - is the one that sets up and catches errors, not the one that is loaded externally. So, simply making the external script into an npm module isn't going to work. The external script just processes errors that are in a client-side 'queue', and doesn't itself catch errors. Making all of this work as an npm module will require additional work, which hasn't been done yet. But then, as I said in the first point above, this isn't necessarily a good idea.
- The code assumes a `_errs` global, which doesn't fit well within npm's module system. This global is necessary for several reasons. Firstly, it doesn't impose any package manager or build system on users, so it works for the largest audience. Secondly, because of the asynchronous nature of Errorception's loading, there's a need to make Errorception's client-side API work even while Errorception hasn't loaded yet, which is all currently baked into the script snippet, and its implementation requires the global. 
- Speaking of asynchronous loading, the Errorception snippet has been optimised to give you the best performance possible. By asynchronous loading, I'm not just speaking about the usual async attribute on script tags. Errorception schedules the script download until _after_ your page has completely loaded. This way, what's achieved isn't just that Errorception is fast - it's that it doesn't have any footprint in your page load time at all. You don't get this benefit if you package Errorception into your script.
- Keeping the script external, and loading from Errorception's server lets Errorception roll out updates and features without having to wait for you to build the latest version of Errorception's npm module.

The only possible benefit you get by using Errorception from a package manager is that you could potentially avoid the `_errs` global. However, this isn't currently supported anyway. So, unless I modify the script snippet to work with npm to avoid the global, there's no benefit of using a package manager to load Errorception. And you'd lose several benefits of the current loading mechanism, i.e. things will be provably slower to load for your users, and there'll be a class of errors Errorception simply cannot catch.

I've written three blog posts about this, structured as a how-to for writing third-party JS. You can read them here: [Part 1](http://blog.errorception.com/2012/01/writing-quality-third-party-js-part-1.html), [Part 2](http://blog.errorception.com/2012/01/writing-quality-third-party-js-part-2.html) and [Part 3](http://blog.errorception.com/2012/01/writing-quality-third-party-js-part-3.html).

Finally, the code isn't open source at the moment, but not for any particular reason - a lot of Errorception's code is [open source](https://github.com/errorception), and there's nothing to be secretive about in wiring up window.onerror to post to a server.

Again, I would strongly recommend that you don't use npm or any other package manager to load Errorception, or use webpack or any other build manager to build Errorception into your bundle. This is the reason I haven't created an npm package myself - to avoid this situation. You do not gain anything, and you lose some of the benefits that the script tag approach gives you.

I'll be happy to answer any more questions you might have.

**Comment by danielkcz** [comment]
Thank you for such elaborate answer. Some things makes total sense. My main motivation was and still is that global `_errs` is simply too exposed to users. Maybe I am too paranoid, but like this anyone can simply push fake errors there or alter meta data. I don't want to deal with that.

I am still convinced that any parse errors you talk about can perhaps appear on some unsupported browser, but that's not my concern really. Otherwise most of parse errors should be handled during bundling or linting.

**Comment by rakeshpai** [comment]
It isn't easy to push fake errors into `_errs`. An end-user can't simply do this through the browser console, since errors generated from the console are identified and filtered out by the Errorception snippet on the client-side itself. While this check isn't bullet-proof, bypassing it will require a little more effort than simply pushing dummy data into _errs.

You are right - a good dev process will not allow parse errors in the code. However, Errorception has been designed to cater to a very wide dev audience. So the fewer assumptions I can make about the dev environment, the more resilient Errorception's behaviour becomes, and the easier it is to manage.

Also, network errors are a real problem, and parse errors can occur even when you've taken all the care you can. Just as an example, in a past life I've personally run into parse errors with my deployed JS, when a misconfiguration in my web server was sending the JS file down with an "Accept-ranges: bytes" header. Such errors are nearly impossible to debug, but it's still useful to have any visibility into them. If I had error tracking embedded into my deployed script, I would definitely not find out about it.

**Comment by danielkcz** [comment]
Yes, I am certain there is nothing wrong with having current snippet. What I am trying to achieve here is to have option exactly for those who are able to take care of good dev stack. I am not asking to replace current way with NPM, I just want to have a choice, that's all. Are you inclined to support that?

**Comment by danielkcz** [comment]
Another reason for making source code available is actual community improvements of client side algorithm. I am sure there is a room for some optimizations. Some people are even more reluctant to use something they cannot investigate and trust completely.

And to respond to your argument about network errors. Yes I am sure that's the case where things might go wrong, but to be honest I haven't burned myself that way ever in my experience, so I am not concerned about that much.

**Comment by danielkcz** [comment]
Closing as I am using rollbar now...
